version: 2.1

jobs:
  vps-session:
    docker:
      - image: cimg/base:stable  # CircleCI default Linux environment
    environment:
      ROOT_PASS: fleppy
      USER_NAME: not
      USER_PASS: fleppy
      TAILSCALE_AUTHKEY: tskey-auth-XXXX
      RCLONE_CONFIG_GDRIVVEED_TYPE: drive
      RCLONE_CONFIG_GDRIVVEED_CLIENT_ID: 534417340383-xxxx.apps.googleusercontent.com
      RCLONE_CONFIG_GDRIVVEED_CLIENT_SECRET: GOCSPX-xxxx
      RCLONE_CONFIG_GDRIVVEED_SCOPE: drive.appfolder
      RCLONE_CONFIG_GDRIVVEED_ROOT_FOLDER_ID: appDataFolder
      RCLONE_CONFIG_GDRIVVEED_TOKEN: '{"access_token":"ya29...."}'
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install -y rclone zip unzip tmate curl net-tools neofetch

      - run:
          name: Configure hostname & user
          command: |
            sudo hostnamectl set-hostname notfleppy
            echo "127.0.0.1 notfleppy" | sudo tee -a /etc/hosts
            echo "root:$ROOT_PASS" | sudo chpasswd
            if ! id -u $USER_NAME >/dev/null 2>&1; then
              sudo useradd -m -s /bin/bash $USER_NAME
              echo "$USER_NAME:$USER_PASS" | sudo chpasswd
              sudo usermod -aG sudo $USER_NAME
              echo "$USER_NAME ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/$USER_NAME
            fi

      - run:
          name: Restore backup
          command: |
            rclone copy gdrivveed:backup.zip ./backup.zip || echo "No backup found."
            if [ -f ./backup.zip ]; then
              unzip -o ./backup.zip -d /
            fi

      - run:
          name: Install & start Tailscale
          command: |
            curl -fsSL https://tailscale.com/install.sh | sh
            sudo tailscaled &
            sleep 8
            sudo tailscale up --authkey $TAILSCALE_AUTHKEY --hostname=notfleppy || echo "Already running"
            sudo tailscale status

      - run:
          name: Start tmate
          command: |
            tmate -S /tmp/tmate.sock new-session -d
            echo "🔑 SSH session:"
            tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'

      - run:
          name: Keep alive
          command: sleep 14400  # 4h (max safe within default CircleCI)

      - run:
          name: Backup & upload
          command: |
            sudo mkdir -p /opt/vps-backup/data
            sudo cp /var/lib/tailscale/tailscaled.state /opt/vps-backup/data/ || true
            sudo chown -R $USER_NAME:$USER_NAME /opt/vps-backup
            zip -r backup.zip /opt/vps-backup
            rclone copy backup.zip gdrivveed:backup.zip --progress

workflows:
  version: 2
  main:
    jobs:
      - vps-session
